CREATE TABLE member
(
    member_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email       VARCHAR(255)                            NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    provider    VARCHAR(255)                            NOT NULL,
    provider_id VARCHAR(255),
    CONSTRAINT pk_member PRIMARY KEY (member_id)
);