CREATE TABLE account
(
    member_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email       VARCHAR(255)                            NOT NULL,
    password    VARCHAR(255),
    name        VARCHAR(255)                            NOT NULL,
    provider    VARCHAR(255)                            NOT NULL,
    provider_id VARCHAR(255),
    CONSTRAINT pk_account PRIMARY KEY (member_id)
);

CREATE TABLE account_roles
(
    account_member_id BIGINT NOT NULL,
    roles             VARCHAR(255)
);

CREATE TABLE refresh_token
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rt_key   VARCHAR(255)                            NOT NULL,
    rt_value VARCHAR(255),
    CONSTRAINT pk_refreshtoken PRIMARY KEY (id, rt_key)
);

ALTER TABLE account_roles
    ADD CONSTRAINT fk_account_roles_on_account FOREIGN KEY (account_member_id) REFERENCES account (member_id);

DROP TABLE member CASCADE;