ALTER TABLE account_roles
DROP
CONSTRAINT fkqeiqpoblkj3ago8dfsgal4dmb;

ALTER TABLE account_roles
DROP
CONSTRAINT fktp61eta5i06bug3w1qr6286uf;

CREATE TABLE project_tags
(
    project_id BIGINT NOT NULL,
    tag        VARCHAR(255)
);

CREATE TABLE projects
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    image_url  VARCHAR(255),
    start_date date,
    CONSTRAINT pk_projects PRIMARY KEY (id)
);

ALTER TABLE account_roles
    ADD account_account_id BIGINT;

ALTER TABLE account_roles
    ALTER COLUMN account_account_id SET NOT NULL;

ALTER TABLE account
    ADD account_id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE account_roles
    ADD CONSTRAINT fk_account_roles_on_account FOREIGN KEY (account_account_id) REFERENCES account (account_id);

ALTER TABLE project_tags
    ADD CONSTRAINT fk_project_tags_on_project FOREIGN KEY (project_id) REFERENCES projects (id);

DROP TABLE member_roles CASCADE;

ALTER TABLE account
DROP
COLUMN member_id;

ALTER TABLE account
DROP
COLUMN id;

ALTER TABLE account_roles
DROP
COLUMN account_id;

ALTER TABLE account_roles
DROP
COLUMN account_member_id;

ALTER TABLE refresh_token
    ALTER COLUMN rt_key DROP NOT NULL;

ALTER TABLE account
    ADD CONSTRAINT pk_account PRIMARY KEY (account_id);

ALTER TABLE refresh_token
    ADD CONSTRAINT pk_refresh_token PRIMARY KEY (id);