spring:
  config:
    import:
      - optional:file:dev-secret.env[.properties]
      - classpath:/ymls-dev/secret.yml
      - classpath:/ymls-dev/basic.yml
      - classpath:/ymls-dev/log.yml
  profiles:
    active: local
    group:
      local: local, common, secret
      blue: blue, common, secret
      green: green, common, secret

---

spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    root: info

server:
  port: 8080
  serverAddress: localhost

serverName: local_server




  #  jpa:
#    open-in-view: on
#    properties:
#      hibernate:
#        show-sql: true
#        format_sql: false
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#  provider:
#    google:
#      authorization-uri: https://accounts.google.com/o/oauth2/auth
#      token-uri: https://oauth2.googleapis.com/token
#      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
#      user-name-attribute: email
  #          github:
#            client-id: ${GITHUB_CLIENT_ID}
#            client-secret: ${GITHUB_CLIENT_SECRET}