spring:
  config:
    import: optional:file:.env[.properties]
#  security:
#    oauth2:
#      authorizationserver:
#        client:${BASE_URL}

#  datasource:
#    url: jdbc:postgresql://localhost:5432/${DB}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    driver-class-name: org.postgresql.Driver
#  jwt:
#    secret: ${JWT_SECRET}
#
#oauth2:
#  google:
#    client-id: ${GOOGLE_CLIENT_ID}
#    client-secret: ${GOOGLE_CLIENT_SECRET}
#    redirect-uri: http://localhost:8080/oauth2/code/google
#    authorization-grant-type: authorization_code
#    scope: profile, email
#  naver:
#    client-id: ${NAVER_CLIENT_ID}
#    client-secret: ${NAVER_CLIENT_SECRET}
#  kakao:
#    client-id: ${KAKAO_CLIENT_ID}
#    client-secret: ${KAKAO_CLIENT_SECRET}
#  github:
#    client-id: ${GITHUB_CLIENT_ID}
#    client-secret: ${GITHUB_CLIENT_SECRET}
#
#spring:
#  config:
#    import: optional:file:.env[.properties]
#  datasource:
#      url: jdbc:postgresql://localhost:5432/${DB}
#      username: ${DB_USERNAME}
#      password: ${DB_PASSWORD}
#      driver-class-name: org.postgresql.Driver
#jwt:
#  secret: ${JWT_SECRET}
#
#oauth2:
#  google:
#    client-id: ${GOOGLE_CLIENT_ID}
#    client-secret: ${GOOGLE_CLIENT_SECRET}
#  naver:
#    client-id: ${NAVER_CLIENT_ID}
#    client-secret: ${NAVER_CLIENT_SECRET}
#  kakao:
#    client-id: ${KAKAO_CLIENT_ID}
#    client-secret: ${KAKAO_CLIENT_SECRET}
#  github:
#    client-id: ${GITHUB_CLIENT_ID}
#    client-secret: ${GITHUB_CLIENT_SECRET}

#cloud:
#  aws:
#    s3:
#      bucket: ${S3_BUCKET}
#    region:
#      static: ${AWS_REGION_STATIC}
#    credentials:
#      access-key: ${AWS_ACCESS_KEY}
#      secret-key: ${AWS_SECRET_KEY}