CREATE TABLE interest_tech_stack
(
    interest_tech_stack_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id              VARCHAR(255),
    tech_stack_id          VARCHAR(255),
    CONSTRAINT pk_interesttechstack PRIMARY KEY (interest_tech_stack_id)
);

CREATE TABLE member
(
    member_id        VARCHAR(255) NOT NULL,
    created_date     TIMESTAMP WITHOUT TIME ZONE,
    modified_date    TIMESTAMP WITHOUT TIME ZONE,
    provider         VARCHAR(255),
    member_email     VARCHAR(255),
    member_nickname  VARCHAR(255),
    profile_url      VARCHAR(255),
    role             VARCHAR(255) NOT NULL,
    member_introduce VARCHAR(255),
    member_position  VARCHAR(255),
    member_career    INTEGER,
    CONSTRAINT pk_member PRIMARY KEY (member_id)
);

CREATE TABLE project_image
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url           VARCHAR(255),
    created_date  TIMESTAMP WITHOUT TIME ZONE,
    modified_date TIMESTAMP WITHOUT TIME ZONE,
    project_id    BIGINT,
    CONSTRAINT pk_projectimage PRIMARY KEY (id)
);

CREATE TABLE project_tags
(
    project_id BIGINT NOT NULL,
    tag        VARCHAR(255)
);

CREATE TABLE projects
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    image_url  VARCHAR(255),
    start_date date,
    CONSTRAINT pk_projects PRIMARY KEY (id)
);

CREATE TABLE refresh_token
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date  TIMESTAMP WITHOUT TIME ZONE,
    modified_date TIMESTAMP WITHOUT TIME ZONE,
    refresh_token VARCHAR(255),
    expired_time  TIMESTAMP WITHOUT TIME ZONE,
    member_id     VARCHAR(255),
    CONSTRAINT pk_refreshtoken PRIMARY KEY (id)
);

CREATE TABLE tech_stack
(
    tech_stack_id VARCHAR(255) NOT NULL,
    created_date  TIMESTAMP WITHOUT TIME ZONE,
    modified_date TIMESTAMP WITHOUT TIME ZONE,
    icon_url      VARCHAR(255),
    CONSTRAINT pk_techstack PRIMARY KEY (tech_stack_id)
);

ALTER TABLE interest_tech_stack
    ADD CONSTRAINT uc_afd744fd2ff2ae3369ff005ac UNIQUE (member_id, tech_stack_id);

ALTER TABLE refresh_token
    ADD CONSTRAINT uc_refreshtoken_member UNIQUE (member_id);

ALTER TABLE interest_tech_stack
    ADD CONSTRAINT FK_INTERESTTECHSTACK_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE interest_tech_stack
    ADD CONSTRAINT FK_INTERESTTECHSTACK_ON_TECH_STACK FOREIGN KEY (tech_stack_id) REFERENCES tech_stack (tech_stack_id);

ALTER TABLE project_image
    ADD CONSTRAINT FK_PROJECTIMAGE_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (id);

ALTER TABLE refresh_token
    ADD CONSTRAINT FK_REFRESHTOKEN_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE project_tags
    ADD CONSTRAINT fk_project_tags_on_project FOREIGN KEY (project_id) REFERENCES projects (id);