CREATE TABLE project_tags
(
    project_id BIGINT NOT NULL,
    tag        VARCHAR(255)
);

CREATE TABLE projects
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    image_url  VARCHAR(255),
    start_date date,
    CONSTRAINT pk_projects PRIMARY KEY (id)
);

ALTER TABLE project_tags
    ADD CONSTRAINT fk_project_tags_on_project FOREIGN KEY (project_id) REFERENCES projects (id);

DROP TABLE member_roles CASCADE;