CREATE TABLE accounts
(
    account_id       BIGINT NOT NULL,
    email            VARCHAR(255),
    birthdate        date,
    nickname         VARCHAR(255),
    oauth_type       VARCHAR(255),
    user_role        VARCHAR(255),
    signup_date      TIMESTAMP WITHOUT TIME ZONE,
    profile_s3_key   VARCHAR(255),
    banned_date      TIMESTAMP WITHOUT TIME ZONE,
    first_login_date TIMESTAMP WITHOUT TIME ZONE,
    last_login_date  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_accounts PRIMARY KEY (account_id)
);

CREATE TABLE project_tags
(
    project_id BIGINT NOT NULL,
    tag        VARCHAR(255)
);

CREATE TABLE projects
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    image_url  VARCHAR(255),
    start_date date,
    CONSTRAINT pk_projects PRIMARY KEY (id)
);

CREATE TABLE refresh_token
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rt_key   VARCHAR(255),
    rt_value VARCHAR(255),
    CONSTRAINT pk_refresh_token PRIMARY KEY (id)
);

ALTER TABLE project_tags
    ADD CONSTRAINT fk_project_tags_on_project FOREIGN KEY (project_id) REFERENCES projects (id);