ALTER TABLE account_roles
DROP
CONSTRAINT fk_account_roles_on_account;

CREATE TABLE accounts
(
    account_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email       VARCHAR(255)                            NOT NULL,
    password    VARCHAR(255),
    name        VARCHAR(255)                            NOT NULL,
    provider    VARCHAR(255)                            NOT NULL,
    provider_id VARCHAR(255),
    CONSTRAINT pk_accounts PRIMARY KEY (account_id)
);

CREATE TABLE accounts_roles
(
    accounts_account_id BIGINT NOT NULL,
    roles               VARCHAR(255)
);

ALTER TABLE accounts_roles
    ADD CONSTRAINT fk_accounts_roles_on_account FOREIGN KEY (accounts_account_id) REFERENCES accounts (account_id);

DROP TABLE account CASCADE;

DROP TABLE account_roles CASCADE;